name: API Tests - Newman

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Rodar testes e gerar relatório
        run: |
          newman run Carrefour.postman_collection.json \
          -e carrefour_env.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export report.html

      - name: Upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html